# config/settings.yaml

# Pengaturan model
model:
  path: "../models/best.pt"  # Path relatif dari folder src ke model
  confidence_threshold: 0.5
  iou_threshold: 0.45

# Pengaturan kamera
camera:
  id: 0              # ID kamera default (0 untuk webcam utama)
  width: 640
  height: 480
  fps: 30

# Pengaturan output
output:
  save_detections: true
  save_video: false
  video_codec: "mp4v"  # Codec untuk menyimpan video

# Tampilan
display:
  show_fps: true
  show_labels: true
  show_confidence: true
  font_scale: 0.7
  thickness: 2
  box_color: [0, 255, 0]    # RGB
  text_color: [255, 255, 255]  # RGB

# Pengaturan aplikasi
app:
  debug_mode: false
  log_level: "INFO"
